POST http://localhost:4000/student-api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###

POST http://localhost:4000/coord-api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###
POST http://localhost:4000/admin-api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

### admin registration
POST http://localhost:4000/admin-api/admin
Content-Type: application/json

{
    "name": "abhinav",
    "email": "abhinavsai.janipireddy@gmail.com"
}

### student registration through admin api
POST http://localhost:4000/admin-api/student
Content-Type: application/json

{
    "name": "Abhinav",
    "email": "abhinavsai.janipireddy@gmail.com",
    "rollno": "22071A1201",
    "phone": "1234567890",
    "gender": "male",
    "dob": "2004-10-21",
    "address": "test address",
    "course": "IT",
    "section": "A",
    "year": "2022",
    "caste": "Peraka",
    "religion": "Muslim",
    "parentName": "Allam Nagaraju",
    "parentPhone": "1234567890"
}

### student update

PUT http://localhost:4000/student-api/update
Content-Type: application/json

{
    "name": "Abhinav",
    "email": "abhinavsai.janipireddy@gmail.com",
    "rollno": "22071A1201",
    "phone": "637382622821",
    "gender": "male",
    "dob": "2004-10-21",
    "address": "Ameerpet",
    "course": "IT",
    "section": "A",
    "year": "2022",
    "caste": "Peraka",
    "religion": "Muslim",
    "parentName": "Allam Nagaraju",
    "parentPhone": "0987654321",
    "hasPhoto": "false",
    "profilePhoto":"",
    "todos":[],
    "classId": "ITA1"
}

### coordinator registration through admin api

POST http://localhost:4000/admin-api/coord
Content-Type: application/json

{
    "name": "abhinav",
    "email": "abhinavsai.janipireddy@gmail.com",
    "rollno": "22071A1227",
    "phone": "1234567890",
    "gender": "male",
    "dob": "2004-05-25",
    "address": "test address",
    "course": "test course",
    "yearOfJoin": "2020",
    "designation": "test designation",
    "qualification": "test qualification"
}

### coordinator update

PUT http://localhost:4000/coord-api/update
Content-Type: application/json

{
    "name": "srinitha",
    "email": "srinithadevaraneni21@gmail.com",
    "rollno": "22071A1227",
    "password": "123456",
    "phone": "1234567890",
    "gender": "female",
    "dob": "2000-01-01",
    "address": "test address",
    "course": "test course",
    "yearOfJoin": "2022",
    "designation": "test designation",
    "qualification": "test qualification"
}

### search for a student by admin
GET http://localhost:4000/admin-api/student/22071A1227

### search for a coordinator by admin
GET http://localhost:4000/admin-api/coord/22071A1227

### making an announcement

POST http://localhost:4000/coord-api/announce
Content-Type: application/json

{
    "title": "Assignement",
    "content": "Please complete it by this week",
    "date": "{{$datetime iso8601}}",
    "creator":"MS. saraswathi"
}

### seeing the announcements

GET http://localhost:4000/student-api/announce

### list of coords

GET http://localhost:4000/admin-api/coords

### list of students

GET http://localhost:4000/admin-api/students

### updating the student by adding photo and changing hasPhoto prop to true.

PUT http://localhost:4000/student-api/profile-photo
Content-Type: application/json

{
    "name": "Vashta",
    "email": "avvarma31@gmail.com",
    "rollno": "22071A1201",
    "phone": "637382622821",
    "gender": "male",
    "dob": "2004-10-21",
    "address": "Ameerpet",
    "course": "IT",
    "section": "A",
    "year": "2022",
    "caste": "Peraka",
    "religion": "Muslim",
    "parentName": "Allam Nagaraju",
    "parentPhone": "0987654321",
    "hasPhoto": "true",
    "profilePhoto":"ashbduabhdsiahbdiadasjadnaskjdaskasndkandksjdadsdasdasidunaidnaiduaidubd"
}

### delete todo by student
PUT http://localhost:4000/student-api/todo/delete/abhinavsai.janipireddy@gmail.com
Content-Type: application/json

{
    "todoId": "vXHphPU_vWIsFgHqN9m_X"
}

### get class details
GET http://localhost:4000/student-api/classInfo/ITA1


