POST http://localhost:4000/student-api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}

###

POST http://localhost:4000/coord-api/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}




###

GET http://localhost:4000/student-api/students
###
